version: "2"
services:
  master:
    image: eeacms/jenkins-master
    ports:
    - "8090:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: jenkins/ssh-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8090"
      JENKINS_NAME: "worker"
      JENKINS_USER: "prateekjain87"
      JENKINS_PASS: "ubuntu"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker:
